server:
  port: 7001

spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: replica1
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://replica2:7002/eureka/

info:
  remark: 这是第一个eureka
  author: God

